import { FormEvent, ReactNode, useEffect, useRef, useState } from 'react'
import { BookOpen, CalendarDays, ChevronLeft, Clock3, FileText, Home, ImagePlus, LogOut, Menu, Mic, Pause, Play, Plus, RotateCcw, Search, Settings, Square, Users, WandSparkles, X } from 'lucide-react'
import { Link, NavLink, Route, Routes, useLocation, useNavigate, useParams } from 'react-router-dom'
import { api, ApiError } from './api'
import type { EventDraft, EventItem, StructureResult, Student } from './types'

const categories = ['课堂表现', '作业', '午休纪律', '表扬', '师生沟通', '家校沟通', '其他']

function cn(...items: (string | false | undefined)[]) { return items.filter(Boolean).join(' ') }
function localInputDate(date = new Date()) { const shifted = new Date(date.getTime() - date.getTimezoneOffset() * 60000); return shifted.toISOString().slice(0, 16) }
function formatDate(value: string, withTime = true) { return new Intl.DateTimeFormat('zh-CN', { month: 'long', day: 'numeric', ...(withTime ? { hour: '2-digit', minute: '2-digit', hour12: false } : {}) }).format(new Date(value)) }

type ASRName = 'paraformer' | 'sensevoice'
type ASRStatus = { provider: ASRName; hotword_count: number; providers: { name: ASRName; installed: boolean; loaded: boolean }[] }

function Avatar({ student, size = 'normal' }: { student: Pick<Student, 'name' | 'avatar_url'>; size?: 'small' | 'normal' | 'large' }) {
  return student.avatar_url ? <img className={`avatar avatar-${size}`} src={student.avatar_url} alt={`${student.name}的照片`} /> : <div className={`avatar avatar-${size} avatar-fallback`}>{student.name.slice(-2)}</div>
}

function Login({ onLogin }: { onLogin: () => void }) {
  const [error, setError] = useState('')
  const [busy, setBusy] = useState(false)
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy(true); setError('')
    const data = new FormData(event.currentTarget)
    try { await api('/auth/login', { method: 'POST', body: JSON.stringify({ username: data.get('username'), password: data.get('password') }) }); onLogin() }
    catch (err) { setError(err instanceof Error ? err.message : '登录失败') }
    finally { setBusy(false) }
  }
  return <main className="login-shell"><section className="login-card">
    <div className="brand-mark"><BookOpen size={27} /><span>StudentLog</span></div>
    <p className="eyebrow">本地学生档案</p><h1>把每天值得记下的事，妥帖地留在这里。</h1>
    <form onSubmit={submit}><label>用户名<input name="username" defaultValue="admin" autoComplete="username" required /></label><label>密码<input name="password" type="password" autoComplete="current-password" required autoFocus /></label>{error && <p className="form-error">{error}</p>}<button className="primary wide" disabled={busy}>{busy ? '正在登录…' : '进入档案'}</button></form>
    <p className="privacy-note">数据保存在这台电脑上，不会自动上传云端。</p>
  </section></main>
}

function Shell({ children, logout }: { children: ReactNode; logout: () => void }) {
  const [open, setOpen] = useState(false); const location = useLocation(); useEffect(() => setOpen(false), [location.pathname])
  const nav = <><div className="side-brand"><div className="brand-icon"><BookOpen size={22} /></div><span>StudentLog</span></div><nav><NavLink to="/"><Home />首页</NavLink><NavLink to="/students"><Users />学生档案</NavLink><NavLink to="/events"><FileText />全部记录</NavLink></nav><div className="side-bottom"><NavLink className="nav-button" to="/settings"><Settings />系统设置</NavLink><button className="nav-button" onClick={logout}><LogOut />退出登录</button><div className="local-badge"><span />本机数据</div></div></>
  return <div className="app-shell"><aside className={cn('sidebar', open && 'open')}>{nav}</aside>{open && <button className="scrim" aria-label="关闭菜单" onClick={() => setOpen(false)} />}<header className="mobile-head"><button className="icon-button" onClick={() => setOpen(true)}><Menu /></button><strong>StudentLog</strong><span /></header><main className="content">{children}</main></div>
}

function PageHeader({ eyebrow, title, action }: { eyebrow?: string; title: string; action?: ReactNode }) { return <header className="page-header"><div>{eyebrow && <p className="eyebrow">{eyebrow}</p>}<h1>{title}</h1></div>{action}</header> }

function HomePage() {
  const [events, setEvents] = useState<EventItem[]>([]); const [students, setStudents] = useState<Student[]>([])
  useEffect(() => { void Promise.all([api<EventItem[]>('/events'), api<Student[]>('/students?recent=true')]).then(([e, s]) => { setEvents(e); setStudents(s) }) }, [])
  const today = new Intl.DateTimeFormat('zh-CN', { month: 'long', day: 'numeric', weekday: 'long' }).format(new Date())
  return <><PageHeader eyebrow={today} title="今天，记录什么？" />
    <section className="quick-grid"><Link to="/record/text" className="quick-card quick-primary"><span className="quick-icon"><Plus /></span><div><strong>文字记录</strong><small>快速保存或 AI 整理</small></div></Link><Link to="/record/voice" className="quick-card"><span className="quick-icon"><Mic /></span><div><strong>语音记录</strong><small>说完后检查再保存</small></div></Link><Link to="/students" className="quick-card"><span className="quick-icon"><Users /></span><div><strong>学生档案</strong><small>按照片或姓名查找</small></div></Link></section>
    <section className="section-block"><div className="section-title"><h2>最近记录</h2><Link to="/events">查看全部</Link></div>{events.length ? <div className="event-list">{events.slice(0, 5).map(event => <EventRow key={event.id} event={event} />)}</div> : <Empty icon={<FileText />} title="还没有记录" detail="第一条记录可以很简单，比如“今天物理课主动回答问题”。" action={<Link className="primary" to="/events/new">写第一条</Link>} />}</section>
    {students.some(s => s.last_event_at) && <section className="section-block"><div className="section-title"><h2>最近记录的学生</h2></div><div className="recent-students">{students.filter(s => s.last_event_at).slice(0, 6).map(student => <Link to={`/students/${student.id}`} key={student.id}><Avatar student={student} /><span><strong>{student.name}</strong><small>{student.event_count} 条记录</small></span></Link>)}</div></section>}
  </>
}

function StudentsPage() {
  const [students, setStudents] = useState<Student[]>([]); const [q, setQ] = useState(''); const [showForm, setShowForm] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('')
  const load = () => api<Student[]>(`/students?q=${encodeURIComponent(q)}`).then(setStudents).catch(e => setError(e.message)); useEffect(() => { void load() }, [q])
  async function add(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); try { await api('/students', { method: 'POST', body: JSON.stringify({ student_no: data.get('student_no'), name: data.get('name'), aliases: [] }) }); form.reset(); setShowForm(false); await load() } catch (e) { setError((e as Error).message) } }
  async function importList(file?: File) { if (!file) return; const body = new FormData(); body.append('file', file); try { await api('/students/import', { method: 'POST', body }); await load() } catch (e) { setError((e as Error).message) } }
  async function clearStudents() { if (!students.length || !confirm('确定清空当前学生名单吗？\n\n没有事件记录的学生将被删除；已有事件记录的学生会被归档，历史记录不会丢失。')) return; setError(''); setNotice(''); try { const result = await api<{ deleted: number; archived: number }>('/students/clear', { method: 'DELETE' }); setNotice(`名单已清空：删除 ${result.deleted} 名无记录学生，归档 ${result.archived} 名有历史记录学生。`); await load() } catch (e) { setError((e as Error).message) } }
  return <><PageHeader eyebrow={`${students.length} 名在册学生`} title="学生档案" action={<div className="header-actions"><button className="secondary danger-outline" onClick={() => void clearStudents()}>清空名单</button><button className="primary" onClick={() => setShowForm(true)}><Plus />新增学生</button></div>} />
    <div className="toolbar"><label className="search"><Search /><input value={q} onChange={e => setQ(e.target.value)} placeholder="搜索姓名或学号" /></label><label className="secondary file-button">导入名单<input type="file" accept=".txt,.csv" onChange={e => void importList(e.target.files?.[0])} /></label></div>{error && <p className="form-error">{error}</p>}{notice && <p className="settings-message">{notice}</p>}
    {students.length ? <div className="student-grid">{students.map(student => <Link className="student-card" to={`/students/${student.id}`} key={student.id}><div className="photo-wrap"><Avatar student={student} size="large" /></div><div><h3>{student.name}</h3><p>学号 {student.student_no}</p><span>{student.event_count} 条记录</span></div></Link>)}</div> : <Empty icon={<Users />} title={q ? '没有找到匹配的学生' : '还没有学生'} detail={q ? '试试姓名中的其他字，或输入学号。' : '逐个新增，或导入 TXT / CSV 名单。'} />}
    {showForm && <Modal title="新增学生" onClose={() => setShowForm(false)}><form onSubmit={add} className="form-grid"><label>学号<input name="student_no" required autoFocus /></label><label>姓名<input name="name" required /></label><div className="form-actions"><button type="button" className="text-button" onClick={() => setShowForm(false)}>取消</button><button className="primary">保存学生</button></div></form></Modal>}
  </>
}

function StudentPage() {
  const { id } = useParams(); const nav = useNavigate(); const [student, setStudent] = useState<Student>(); const [events, setEvents] = useState<EventItem[]>([]); const [edit, setEdit] = useState(false); const [error, setError] = useState('')
  const load = () => Promise.all([api<Student>(`/students/${id}`), api<EventItem[]>(`/events?student_id=${id}`)]).then(([s, e]) => { setStudent(s); setEvents(e) }).catch(e => setError(e.message)); useEffect(() => { void load() }, [id])
  async function avatar(file?: File) { if (!file) return; const body = new FormData(); body.append('file', file); try { await api(`/students/${id}/avatar`, { method: 'POST', body }); await load() } catch (e) { setError((e as Error).message) } }
  async function update(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const d = new FormData(event.currentTarget); try { await api(`/students/${id}`, { method: 'PATCH', body: JSON.stringify({ student_no: d.get('student_no'), name: d.get('name'), aliases: String(d.get('aliases') || '').split(/[，,]/).map(x => x.trim()).filter(Boolean) }) }); setEdit(false); await load() } catch (e) { setError((e as Error).message) } }
  async function deactivate() { if (!confirm('停用后，学生不会出现在日常列表中，已有记录会保留。继续吗？')) return; await api(`/students/${id}`, { method: 'DELETE' }); nav('/students') }
  if (!student) return <p>{error || '正在读取档案…'}</p>
  const counts = categories.map(name => ({ name, count: events.filter(e => e.category === name).length })).filter(i => i.count)
  return <><Link to="/students" className="back"><ChevronLeft />返回学生列表</Link><section className="profile-head"><label className="avatar-upload"><Avatar student={student} size="large" /><span><ImagePlus />更换照片</span><input type="file" accept="image/jpeg,image/png,image/webp" onChange={e => void avatar(e.target.files?.[0])} /></label><div className="profile-main"><p className="eyebrow">学生档案</p><h1>{student.name}</h1><p>学号 {student.student_no}</p><div className="counts"><span><strong>{events.length}</strong>全部记录</span>{counts.slice(0, 4).map(item => <span key={item.name}><strong>{item.count}</strong>{item.name}</span>)}</div></div><div className="profile-actions"><Link className="primary" to={`/record/text?student=${student.id}`}><Plus />新增记录</Link><button className="secondary" onClick={() => setEdit(true)}>编辑资料</button></div></section>{error && <p className="form-error">{error}</p>}
    <section className="section-block"><div className="section-title"><h2>事件时间线</h2></div>{events.length ? <div className="timeline">{events.map(event => <EventCard event={event} key={event.id} />)}</div> : <Empty icon={<CalendarDays />} title="时间线还是空的" detail="从一条客观、简短的事件开始记录。" />}</section>
    {edit && <Modal title="编辑学生资料" onClose={() => setEdit(false)}><form onSubmit={update} className="form-grid"><label>学号<input name="student_no" defaultValue={student.student_no} required /></label><label>姓名<input name="name" defaultValue={student.name} required /></label><label className="span-2">姓名别名（逗号分隔）<input name="aliases" defaultValue={student.aliases.join('，')} /></label><div className="danger-zone"><button type="button" className="danger-link" onClick={() => void deactivate()}>停用学生</button></div><div className="form-actions"><button type="button" className="text-button" onClick={() => setEdit(false)}>取消</button><button className="primary">保存修改</button></div></form></Modal>}
  </>
}

function EventsPage() {
  const [events, setEvents] = useState<EventItem[]>([]); const [q, setQ] = useState(''); const [category, setCategory] = useState('')
  useEffect(() => { const p = new URLSearchParams({ q }); if (category) p.set('category', category); void api<EventItem[]>(`/events?${p}`).then(setEvents) }, [q, category])
  return <><PageHeader eyebrow={`${events.length} 条记录`} title="全部记录" action={<Link className="primary" to="/events/new"><Plus />新增记录</Link>} /><div className="toolbar"><label className="search"><Search /><input value={q} onChange={e => setQ(e.target.value)} placeholder="搜索事件内容" /></label><select value={category} onChange={e => setCategory(e.target.value)}><option value="">全部分类</option>{categories.map(c => <option key={c}>{c}</option>)}</select></div>{events.length ? <div className="event-list roomy">{events.map(event => <EventCard event={event} key={event.id} />)}</div> : <Empty icon={<FileText />} title="没有符合条件的记录" detail="调整筛选条件，或新增一条记录。" />}</>
}

function SmartRecordPage() {
  const { mode = 'text' } = useParams(); const isVoice = mode === 'voice'; const nav = useNavigate(); const preset = new URLSearchParams(useLocation().search).get('student')
  const [students, setStudents] = useState<Student[]>([]); const [selected, setSelected] = useState<string[]>(preset ? [preset] : []); const [transcript, setTranscript] = useState(''); const [result, setResult] = useState<StructureResult>(); const [draft, setDraft] = useState<EventDraft>(); const [audio, setAudio] = useState<Blob>(); const [recording, setRecording] = useState<'idle' | 'recording' | 'paused' | 'ready'>('idle'); const [seconds, setSeconds] = useState(0); const [busy, setBusy] = useState(''); const [error, setError] = useState(''); const [asrStatus, setAsrStatus] = useState<ASRStatus>()
  const recorderRef = useRef<MediaRecorder | undefined>(undefined); const streamRef = useRef<MediaStream | undefined>(undefined); const chunksRef = useRef<Blob[]>([]); const cancelledRef = useRef(false)
  useEffect(() => { void api<Student[]>('/students').then(setStudents); if (isVoice) void api<ASRStatus>('/asr/status').then(setAsrStatus); return () => streamRef.current?.getTracks().forEach(track => track.stop()) }, [isVoice])
  useEffect(() => { if (recording !== 'recording') return; const timer = window.setInterval(() => setSeconds(value => value + 1), 1000); return () => clearInterval(timer) }, [recording])
  function toggle(id: string) { setSelected(current => current.includes(id) ? current.filter(item => item !== id) : [...current, id]) }
  async function startRecording() { setError(''); try { const stream = await navigator.mediaDevices.getUserMedia({ audio: true }); streamRef.current = stream; const preferred = ['audio/webm;codecs=opus', 'audio/webm', 'audio/mp4'].find(type => MediaRecorder.isTypeSupported(type)); const recorder = new MediaRecorder(stream, preferred ? { mimeType: preferred } : undefined); chunksRef.current = []; cancelledRef.current = false; recorder.ondataavailable = event => { if (event.data.size) chunksRef.current.push(event.data) }; recorder.onstop = () => { stream.getTracks().forEach(track => track.stop()); if (!cancelledRef.current) { setAudio(new Blob(chunksRef.current, { type: recorder.mimeType })); setRecording('ready') } }; recorder.start(500); recorderRef.current = recorder; setSeconds(0); setAudio(undefined); setRecording('recording') } catch { setError('无法使用麦克风，请检查浏览器权限。') } }
  function pauseOrResume() { const recorder = recorderRef.current; if (!recorder) return; if (recorder.state === 'recording') { recorder.pause(); setRecording('paused') } else { recorder.resume(); setRecording('recording') } }
  function finishRecording() { if (recorderRef.current?.state !== 'inactive') recorderRef.current?.stop() }
  function cancelRecording() { cancelledRef.current = true; if (recorderRef.current?.state !== 'inactive') recorderRef.current?.stop(); streamRef.current?.getTracks().forEach(track => track.stop()); setAudio(undefined); setSeconds(0); setRecording('idle') }
  async function structure(source = transcript) { if (!source.trim()) { setError('请先输入或转写一段记录'); return } setBusy('正在整理事件…'); setError(''); try { const response = await api<StructureResult>('/ai/structure', { method: 'POST', body: JSON.stringify({ transcript: source, preset_student_id: preset }) }); setResult(response); setDraft(response.draft); setSelected(response.draft.student_ids) } catch (e) { setError((e as Error).message) } finally { setBusy('') } }
  async function transcribeAndStructure() { if (!audio) return; const current = asrStatus?.providers.find(item => item.name === asrStatus.provider); setBusy(current?.loaded ? '正在本地识别…' : '正在初始化本地语音识别…'); setError(''); try { const body = new FormData(); body.append('file', audio, `recording.${audio.type.includes('mp4') ? 'm4a' : 'webm'}`); const asr = await api<{ transcript: string; provider: string; elapsed_ms: number; hotword_count: number; name_corrections: { original: string; corrected: string }[] }>('/asr/transcribe', { method: 'POST', body }); setTranscript(asr.transcript); await structure(asr.transcript); const corrected = asr.name_corrections.length ? ` 已按名单校正：${asr.name_corrections.map(item => `${item.original}→${item.corrected}`).join('、')}，请核对。` : ''; setError(`${asr.provider === 'paraformer' ? 'Paraformer' : 'SenseVoice'} 本地识别用时 ${(asr.elapsed_ms / 1000).toFixed(1)} 秒，已使用 ${asr.hotword_count} 个热词。${corrected}`); void api<ASRStatus>('/asr/status').then(setAsrStatus) } catch (e) { setError((e as Error).message); setBusy('') } }
  async function quickSave() { if (!transcript.trim()) { setError('请输入记录内容'); return } if (!selected.length) { setError('请至少选择一名学生'); return } setBusy('正在保存…'); try { await api('/events', { method: 'POST', body: JSON.stringify({ student_ids: selected, occurred_at: new Date().toISOString(), category: '其他', event_description: transcript.trim(), raw_transcript: transcript.trim(), record_method: 'text', tags: [], ai_processed: false }) }); nav(preset ? `/students/${preset}` : '/events') } catch (e) { setError((e as Error).message); setBusy('') } }
  async function confirmSave() { if (!draft || !selected.length) { setError('请确认至少一名学生'); return } setBusy('正在保存正式记录…'); const scores = result?.candidates.filter(item => selected.includes(item.student_id)).map(item => item.confidence) || []; try { await api('/events', { method: 'POST', body: JSON.stringify({ ...draft, student_ids: selected, raw_transcript: transcript, record_method: isVoice ? 'voice' : 'text', ai_processed: true, ai_confidence: scores.length ? Math.min(...scores) : preset ? 1 : null }) }); nav(preset ? `/students/${preset}` : '/events') } catch (e) { setError((e as Error).message); setBusy('') } }
  function setField<K extends keyof EventDraft>(key: K, value: EventDraft[K]) { setDraft(current => current ? { ...current, [key]: value } : current) }
  const time = `${String(Math.floor(seconds / 60)).padStart(2, '0')}:${String(seconds % 60).padStart(2, '0')}`
  if (draft) return <><button className="back link-button" onClick={() => { setDraft(undefined); setResult(undefined) }}><ChevronLeft />返回原始记录</button><PageHeader eyebrow={result?.provider === 'deepseek' ? 'DeepSeek 整理结果' : 'Mock 整理结果'} title="确认后再保存" /><div className={cn('review-alert', result?.requires_student_confirmation && 'attention')}><strong>{result?.requires_student_confirmation ? '请重点核对学生姓名' : '已找到高置信度学生'}</strong><span>AI 结果尚未写入档案，所有字段都可以修改。</span></div><form className="event-form" onSubmit={e => { e.preventDefault(); void confirmSave() }}><fieldset><legend>关联学生 <span>可多选；候选仅来自本地名单</span></legend><div className="student-picker">{students.map(student => { const candidate = result?.candidates.find(item => item.student_id === student.id); return <button type="button" className={cn(selected.includes(student.id) && 'selected')} key={student.id} onClick={() => toggle(student.id)}><Avatar student={student} size="small" /><span>{student.name}<small>{candidate ? `${Math.round(candidate.confidence * 100)}% · ${candidate.reason}` : student.student_no}</small></span></button> })}</div></fieldset><div className="form-grid"><label>发生时间<input type="datetime-local" value={localInputDate(new Date(draft.occurred_at))} onChange={e => setField('occurred_at', new Date(e.target.value).toISOString())} required /></label><label>分类<select value={draft.category} onChange={e => setField('category', e.target.value)}>{categories.map(c => <option key={c}>{c}</option>)}</select></label><label className="span-2">事件经过<textarea id="draft-description" rows={4} value={draft.event_description} onChange={e => setField('event_description', e.target.value)} required /></label><label>地点<input value={draft.location || ''} onChange={e => setField('location', e.target.value || null)} /></label><label>标签<input value={draft.tags.join('，')} onChange={e => setField('tags', e.target.value.split(/[，,]/).map(item => item.trim()).filter(Boolean))} /></label><label className="span-2">学生回应<textarea rows={2} value={draft.student_response || ''} onChange={e => setField('student_response', e.target.value || null)} /></label><label className="span-2">教师处理<textarea rows={2} value={draft.teacher_action || ''} onChange={e => setField('teacher_action', e.target.value || null)} /></label><label className="span-2">后续措施<textarea rows={2} value={draft.follow_up || ''} onChange={e => setField('follow_up', e.target.value || null)} /></label></div><details className="raw-transcript"><summary>查看原始{isVoice ? '转写' : '输入'}</summary><p>{transcript}</p></details>{error && <p className="form-error">{error}</p>}<div className="sticky-actions"><button type="button" className="secondary" onClick={() => void structure()}><RotateCcw />重新整理</button><button type="button" className="secondary" onClick={() => document.getElementById('draft-description')?.focus()}>编辑</button><button type="submit" className="primary" disabled={!!busy}>{busy || '确认保存'}</button></div></form></>
  return <><Link to={preset ? `/students/${preset}` : '/'} className="back"><ChevronLeft />取消并返回</Link><PageHeader eyebrow={isVoice ? '录音只用于本次转写' : '文字记录'} title={isVoice ? '说完一件事，再检查' : '写下一件事'} />{isVoice ? <section className="recorder-card"><div className={cn('record-orb', recording === 'recording' && 'active')}><Mic /></div><strong>{recording === 'recording' ? '正在录音' : recording === 'paused' ? '录音已暂停' : recording === 'ready' ? '录音完成' : '准备录音'}</strong><time>{time}</time><div className="recorder-actions">{recording === 'idle' && <button className="primary" onClick={() => void startRecording()}><Mic />开始</button>}{(recording === 'recording' || recording === 'paused') && <><button className="secondary" onClick={pauseOrResume}>{recording === 'paused' ? <Play /> : <Pause />}{recording === 'paused' ? '继续' : '暂停'}</button><button className="primary" onClick={finishRecording}><Square />结束</button><button className="text-button" onClick={cancelRecording}>取消</button></>}{recording === 'ready' && <><button className="secondary" onClick={() => void startRecording()}><RotateCcw />重录</button><button className="primary" onClick={() => void transcribeAndStructure()} disabled={!!busy}><WandSparkles />{busy || '转写并整理'}</button></>}</div><p>转写完成后不会保留原始录音。正式使用麦克风时，本地 localhost 可直接获得权限。</p></section> : <section className="text-capture"><textarea rows={7} value={transcript} onChange={e => setTranscript(e.target.value)} placeholder="例如：今天中午一点四十五，杨煜洆在教室午休时和同学讲话……" autoFocus /><fieldset><legend>快速记录关联学生 <span>使用 AI 整理时可暂不选择</span></legend><div className="student-picker compact">{students.map(student => <button type="button" className={cn(selected.includes(student.id) && 'selected')} key={student.id} onClick={() => toggle(student.id)}><Avatar student={student} size="small" /><span>{student.name}<small>{student.student_no}</small></span></button>)}</div></fieldset><div className="capture-actions"><button className="secondary" onClick={() => void quickSave()} disabled={!!busy}>快速保存</button><button className="primary" onClick={() => void structure()} disabled={!!busy}><WandSparkles />{busy || 'AI 整理'}</button></div></section>}{error && <p className="form-error capture-error">{error}</p>}</>
}

function SettingsPage() {
  const [status, setStatus] = useState<ASRStatus>()
  const [saving, setSaving] = useState(false)
  const [message, setMessage] = useState('')

  useEffect(() => { void api<ASRStatus>('/asr/status').then(setStatus).catch(error => setMessage(error.message)) }, [])
  async function choose(provider: ASRName) {
    setSaving(true); setMessage('')
    try {
      await api('/settings/asr', { method: 'PUT', body: JSON.stringify({ provider }) })
      setStatus(await api<ASRStatus>('/asr/status'))
      setMessage('本地语音识别模型已切换。')
    } catch (error) { setMessage((error as Error).message) }
    finally { setSaving(false) }
  }
  return <><PageHeader eyebrow="只保存在这台电脑" title="系统设置" /><section className="settings-panel"><div className="section-title"><div><h2>本地语音识别</h2><p>默认使用 Paraformer；两种模型都只使用 CPU，录音不会上传。</p></div></div>{status ? <div className="provider-grid">{status.providers.map(item => <button key={item.name} disabled={saving} className={cn('provider-card', status.provider === item.name && 'selected')} onClick={() => void choose(item.name)}><span className="provider-choice">{status.provider === item.name ? '已选择' : '选择'}</span><strong>{item.name === 'paraformer' ? 'Paraformer' : 'SenseVoiceSmall'}</strong><small>{item.name === 'paraformer' ? '推荐 · 支持学生姓名热词' : '备选 · 用于对照和回退'}</small><span className={cn('model-state', item.installed && 'ready')}>{item.installed ? item.loaded ? '模型已加载' : '模型已安装，首次使用时加载' : '模型尚未安装'}</span></button>)}</div> : <p>正在读取模型状态…</p>}<div className="settings-note"><strong>热词词典</strong><span>当前包含 {status?.hotword_count ?? '…'} 个学生姓名与场景词；学生新增、改名、停用或导入后会自动刷新。</span></div><div className="settings-note"><strong>模型文件</strong><span>模型放在程序目录的 models/paraformer 与 models/sensevoice 中，不会打进 EXE，也不会在使用录音时静默下载。</span></div>{message && <p className="settings-message">{message}</p>}</section></>
}

function NewEventPage() {
  const params = new URLSearchParams(useLocation().search); const preset = params.get('student'); const nav = useNavigate(); const [students, setStudents] = useState<Student[]>([]); const [selected, setSelected] = useState<string[]>(preset ? [preset] : []); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  useEffect(() => { void api<Student[]>('/students').then(setStudents) }, [])
  function toggle(id: string) { setSelected(current => current.includes(id) ? current.filter(x => x !== id) : [...current, id]) }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!selected.length) { setError('请至少选择一名学生'); return } const d = new FormData(event.currentTarget); setBusy(true); setError(''); try { await api('/events', { method: 'POST', body: JSON.stringify({ student_ids: selected, occurred_at: d.get('occurred_at'), location: d.get('location') || null, category: d.get('category'), event_description: d.get('event_description'), student_response: d.get('student_response') || null, teacher_action: d.get('teacher_action') || null, follow_up: d.get('follow_up') || null, tags: String(d.get('tags') || '').split(/[，,]/).map(x => x.trim()).filter(Boolean), record_method: 'text' }) }); nav(preset ? `/students/${preset}` : '/events') } catch (e) { setError((e as Error).message) } finally { setBusy(false) } }
  return <><Link to={preset ? `/students/${preset}` : '/events'} className="back"><ChevronLeft />取消并返回</Link><PageHeader eyebrow="手工文字记录" title="记下一件事" /><form className="event-form" onSubmit={submit}><fieldset><legend>关联学生 <span>可选择多名</span></legend><div className="student-picker">{students.map(s => <button type="button" className={cn(selected.includes(s.id) && 'selected')} key={s.id} onClick={() => toggle(s.id)}><Avatar student={s} size="small" /><span>{s.name}<small>{s.student_no}</small></span></button>)}</div></fieldset><div className="form-grid"><label>发生时间<input name="occurred_at" type="datetime-local" defaultValue={localInputDate()} required /></label><label>分类<select name="category" defaultValue="其他">{categories.map(c => <option key={c}>{c}</option>)}</select></label><label className="span-2">事件经过<textarea name="event_description" rows={4} placeholder="客观记录发生了什么…" required autoFocus /></label><label>地点<input name="location" placeholder="例如：教室" /></label><label>标签<input name="tags" placeholder="午休，谈话（逗号分隔）" /></label><label className="span-2">学生回应<textarea name="student_response" rows={2} /></label><label className="span-2">教师处理<textarea name="teacher_action" rows={2} /></label><label className="span-2">后续措施<textarea name="follow_up" rows={2} /></label></div>{error && <p className="form-error">{error}</p>}<div className="sticky-actions"><button type="button" className="text-button" onClick={() => nav(-1)}>取消</button><button className="primary" disabled={busy}>{busy ? '正在保存…' : '保存记录'}</button></div></form></>
}

function EditEventPage() {
  const { eventId } = useParams(); const nav = useNavigate(); const [record, setRecord] = useState<EventItem>(); const [students, setStudents] = useState<Student[]>([]); const [selected, setSelected] = useState<string[]>([]); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  useEffect(() => { void Promise.all([api<EventItem>(`/events/${eventId}`), api<Student[]>('/students')]).then(([item, list]) => { setRecord(item); setStudents(list); setSelected(item.students.map(s => s.id)) }).catch(e => setError(e.message)) }, [eventId])
  function toggle(id: string) { setSelected(current => current.includes(id) ? current.filter(x => x !== id) : [...current, id]) }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!selected.length) { setError('请至少选择一名学生'); return } const d = new FormData(event.currentTarget); setBusy(true); try { await api(`/events/${eventId}`, { method: 'PUT', body: JSON.stringify({ student_ids: selected, occurred_at: d.get('occurred_at'), location: d.get('location') || null, category: d.get('category'), event_description: d.get('event_description'), student_response: d.get('student_response') || null, teacher_action: d.get('teacher_action') || null, follow_up: d.get('follow_up') || null, raw_transcript: record?.raw_transcript || null, tags: String(d.get('tags') || '').split(/[，,]/).map(x => x.trim()).filter(Boolean), record_method: record?.record_method || 'text', ai_processed: record?.ai_processed || false, ai_confidence: record?.ai_confidence || null }) }); nav(-1) } catch (e) { setError((e as Error).message); setBusy(false) } }
  if (!record) return <p>{error || '正在读取记录…'}</p>
  return <><button className="back link-button" onClick={() => nav(-1)}><ChevronLeft />取消并返回</button><PageHeader eyebrow="修改已有记录" title="编辑事件" /><form className="event-form" onSubmit={submit}><fieldset><legend>关联学生 <span>可选择多名</span></legend><div className="student-picker">{students.map(s => <button type="button" className={cn(selected.includes(s.id) && 'selected')} key={s.id} onClick={() => toggle(s.id)}><Avatar student={s} size="small" /><span>{s.name}<small>{s.student_no}</small></span></button>)}</div></fieldset><div className="form-grid"><label>发生时间<input name="occurred_at" type="datetime-local" defaultValue={localInputDate(new Date(record.occurred_at))} required /></label><label>分类<select name="category" defaultValue={record.category}>{categories.map(c => <option key={c}>{c}</option>)}</select></label><label className="span-2">事件经过<textarea name="event_description" rows={4} defaultValue={record.event_description} required /></label><label>地点<input name="location" defaultValue={record.location || ''} /></label><label>标签<input name="tags" defaultValue={record.tags.join('，')} /></label><label className="span-2">学生回应<textarea name="student_response" rows={2} defaultValue={record.student_response || ''} /></label><label className="span-2">教师处理<textarea name="teacher_action" rows={2} defaultValue={record.teacher_action || ''} /></label><label className="span-2">后续措施<textarea name="follow_up" rows={2} defaultValue={record.follow_up || ''} /></label></div>{error && <p className="form-error">{error}</p>}<div className="sticky-actions"><button type="button" className="text-button" onClick={() => nav(-1)}>取消</button><button className="primary" disabled={busy}>{busy ? '正在保存…' : '保存修改'}</button></div></form></>
}

function EventRow({ event }: { event: EventItem }) { return <article className="event-row"><time><strong>{new Date(event.occurred_at).toLocaleTimeString('zh-CN', { hour: '2-digit', minute: '2-digit', hour12: false })}</strong><small>{formatDate(event.occurred_at, false)}</small></time><div><p>{event.students.map(s => s.name).join('、')}<span className="category">{event.category}</span></p><small>{event.event_description}</small></div></article> }
function EventCard({ event }: { event: EventItem }) { const [open, setOpen] = useState(false); async function remove() { if (!confirm('删除后无法恢复，确定删除这条记录吗？')) return; await api(`/events/${event.id}`, { method: 'DELETE' }); window.location.reload() } return <article className="event-card" onClick={() => setOpen(!open)}><div className="event-meta"><time><Clock3 />{formatDate(event.occurred_at)}</time>{event.location && <span>{event.location}</span>}<span className="category">{event.category}</span></div><div className="event-students">{event.students.map(s => <Link onClick={e => e.stopPropagation()} to={`/students/${s.id}`} key={s.id}>{s.name}</Link>)}</div><p className="event-description">{event.event_description}</p>{event.tags.length > 0 && <div className="tags">{event.tags.map(tag => <span key={tag}>#{tag}</span>)}</div>}{open && <div className="event-details">{event.student_response && <p><strong>学生回应</strong>{event.student_response}</p>}{event.teacher_action && <p><strong>教师处理</strong>{event.teacher_action}</p>}{event.follow_up && <p><strong>后续措施</strong>{event.follow_up}</p>}<div className="record-actions"><Link to={`/events/${event.id}/edit`} onClick={e => e.stopPropagation()}>编辑记录</Link><button onClick={e => { e.stopPropagation(); void remove() }}>删除</button></div></div>}</article> }
function Empty({ icon, title, detail, action }: { icon: ReactNode; title: string; detail: string; action?: ReactNode }) { return <div className="empty"><span>{icon}</span><h3>{title}</h3><p>{detail}</p>{action}</div> }
function Modal({ title, children, onClose }: { title: string; children: ReactNode; onClose: () => void }) { return <div className="modal-backdrop" onMouseDown={onClose}><section className="modal" onMouseDown={e => e.stopPropagation()} role="dialog" aria-modal="true"><header><h2>{title}</h2><button className="icon-button" onClick={onClose}><X /></button></header>{children}</section></div> }

export default function App() {
  const [auth, setAuth] = useState<'loading' | 'yes' | 'no'>('loading')
  useEffect(() => { void api('/auth/me').then(() => setAuth('yes')).catch((e: ApiError) => setAuth(e.status === 401 ? 'no' : 'no')) }, [])
  async function logout() { await api('/auth/logout', { method: 'POST' }); setAuth('no') }
  if (auth === 'loading') return <div className="app-loading">正在打开本地档案…</div>
  if (auth === 'no') return <Login onLogin={() => setAuth('yes')} />
  return <Shell logout={() => void logout()}><Routes><Route path="/" element={<HomePage />} /><Route path="/students" element={<StudentsPage />} /><Route path="/students/:id" element={<StudentPage />} /><Route path="/events" element={<EventsPage />} /><Route path="/record/:mode" element={<SmartRecordPage />} /><Route path="/settings" element={<SettingsPage />} /><Route path="/events/new" element={<NewEventPage />} /><Route path="/events/:eventId/edit" element={<EditEventPage />} /></Routes></Shell>
}
